"""Minimal GitHub REST integration with no SDK dependency."""

from __future__ import annotations

import base64
from pathlib import PurePosixPath
from typing import Any
from urllib.parse import quote

import httpx

from .schemas import GistRequest, PushRequest

API = "https://api.github.com"


class GitHubService:
    def __init__(
        self,
        token: str,
        *,
        transport: httpx.AsyncBaseTransport | None = None,
        timeout: float = 20,
    ) -> None:
        self.token = token
        self.transport = transport
        self.timeout = timeout

    @property
    def headers(self) -> dict[str, str]:
        return {
            "Authorization": f"Bearer {self.token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
            "User-Agent": "project-thoth-mobile/4.0",
        }

    def _client(self) -> httpx.AsyncClient:
        return httpx.AsyncClient(
            headers=self.headers,
            transport=self.transport,
            timeout=self.timeout,
            follow_redirects=True,
        )

    @staticmethod
    def _rate(response: httpx.Response) -> dict[str, Any]:
        raw = response.headers.get("X-RateLimit-Remaining")
        remaining = int(raw) if raw and raw.isdigit() else None
        return {
            "rate_limit_remaining": remaining,
            "rate_limit_warning": remaining is not None and remaining < 10,
        }

    async def status(self) -> dict[str, Any]:
        if not self.token:
            return {"authenticated": False, "username": "", "scopes": []}
        async with self._client() as client:
            response = await client.get(f"{API}/user")
        if response.status_code in {401, 403}:
            return {
                "authenticated": False,
                "username": "",
                "scopes": [],
                **self._rate(response),
            }
        response.raise_for_status()
        scopes = [item.strip() for item in response.headers.get("X-OAuth-Scopes", "").split(",") if item.strip()]
        return {
            "authenticated": True,
            "username": response.json().get("login", ""),
            "scopes": scopes,
            **self._rate(response),
        }

    async def create_gist(self, request: GistRequest) -> dict[str, Any]:
        self._require_token()
        async with self._client() as client:
            response = await client.post(
                f"{API}/gists",
                json={
                    "description": request.description or "Generated by Project Thoth",
                    "public": request.is_public,
                    "files": {request.filename: {"content": request.code}},
                },
            )
        response.raise_for_status()
        data = response.json()
        return {
            "id": data["id"],
            "url": data["url"],
            "html_url": data["html_url"],
            **self._rate(response),
        }

    async def push_file(self, request: PushRequest) -> dict[str, Any]:
        self._require_token()
        # Pydantic already rejects traversal; PurePosixPath canonicalizes harmless separators.
        path = str(PurePosixPath(request.filename))
        owner_repo = quote(request.repo, safe="/")
        encoded_path = quote(path, safe="/")
        endpoint = f"{API}/repos/{owner_repo}/contents/{encoded_path}"
        async with self._client() as client:
            existing = await client.get(endpoint, params={"ref": request.branch})
            sha: str | None = None
            if existing.status_code == 200:
                sha = existing.json().get("sha")
            elif existing.status_code != 404:
                existing.raise_for_status()
            payload: dict[str, Any] = {
                "message": request.commit_message,
                "content": base64.b64encode(request.code.encode("utf-8")).decode("ascii"),
                "branch": request.branch,
            }
            if sha:
                payload["sha"] = sha
            response = await client.put(endpoint, json=payload)
        response.raise_for_status()
        data = response.json()
        return {
            "commit_sha": data.get("commit", {}).get("sha", ""),
            "file_url": data.get("content", {}).get("html_url", ""),
            **self._rate(response),
        }

    def _require_token(self) -> None:
        if not self.token:
            raise PermissionError("GITHUB_TOKEN is not set in the Termux environment")
