"""Strict wire schemas for every agent exchange."""

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator


class StrictModel(BaseModel):
    model_config = ConfigDict(extra="forbid", strict=True)


class CoderOutput(StrictModel):
    thought_process: str = Field(description="Plan and edge-case considerations.")
    implementation_code: str = Field(description="Self-contained Python 3.10+ code with tests.")


class VerifierOutput(StrictModel):
    status: Literal["APPROVED", "NEEDS_REVISION"]
    implementation_critique: str
    test_critique: str
    suggested_fix: str | None = None

    @model_validator(mode="after")
    def revision_requires_fix(self) -> "VerifierOutput":
        if self.status == "NEEDS_REVISION" and not self.suggested_fix:
            raise ValueError("suggested_fix is required for NEEDS_REVISION")
        return self


class ExecutionResult(StrictModel):
    exit_code: int | None
    stdout: str = ""
    stderr: str = ""
    timed_out: bool = False


class Usage(StrictModel):
    prompt_tokens: int = 0
    completion_tokens: int = 0


class RunRequest(StrictModel):
    prompt: str = Field(min_length=10, max_length=2000)
    provider: Literal["groq", "gemini", "ollama"] = "groq"
    model: str = Field(default="llama-3.1-8b-instant", min_length=1, max_length=200)
    allow_filesystem: bool = False
    allow_network: bool = False
    max_turns: int = Field(default=3, ge=1, le=5)


SSEType = Literal[
    "start",
    "turn_start",
    "coder_start",
    "coder_done",
    "execution_start",
    "execution_done",
    "verifier_start",
    "verifier_done",
    "complete",
    "error",
    "arena_start",
    "candidate_done",
    "judge_start",
    "judge_done",
    "arena_complete",
]


class SSEEvent(StrictModel):
    type: SSEType
    turn_index: int | None = None
    data: dict[str, Any] = Field(default_factory=dict)


class GistRequest(StrictModel):
    code: str = Field(min_length=1, max_length=200_000)
    filename: str = Field(default="thoth_result.py", min_length=1, max_length=120)
    description: str = Field(default="Generated by Project Thoth", max_length=500)
    is_public: bool = False

    @field_validator("filename")
    @classmethod
    def safe_filename(cls, value: str) -> str:
        if "/" in value or "\\" in value or value in {".", ".."}:
            raise ValueError("filename must be a single file name")
        return value


class PushRequest(StrictModel):
    code: str = Field(min_length=1, max_length=200_000)
    filename: str = Field(min_length=1, max_length=240)
    repo: str = Field(pattern=r"^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$")
    branch: str = Field(default="main", min_length=1, max_length=200)
    commit_message: str = Field(default="Add Thoth-generated script", min_length=1, max_length=500)

    @field_validator("filename")
    @classmethod
    def safe_repo_path(cls, value: str) -> str:
        normalized = value.replace("\\", "/")
        if normalized.startswith("/") or ".." in normalized.split("/"):
            raise ValueError("filename must be a safe repository-relative path")
        return normalized


class ArenaCandidateConfig(StrictModel):
    candidate_id: Literal["A", "B", "C"]
    provider: Literal["groq", "gemini", "ollama"]
    model: str = Field(min_length=1, max_length=200)


class ArenaRequest(StrictModel):
    prompt: str = Field(min_length=10, max_length=2000)
    allow_filesystem: bool = False
    allow_network: bool = False
    candidates: list[ArenaCandidateConfig] | None = Field(default=None, min_length=1, max_length=3)

    @model_validator(mode="after")
    def unique_candidates(self) -> "ArenaRequest":
        if self.candidates:
            ids = [item.candidate_id for item in self.candidates]
            if len(ids) != len(set(ids)):
                raise ValueError("candidate IDs must be unique")
        return self


class CandidateScore(StrictModel):
    candidate_id: Literal["A", "B", "C"]
    correctness: int = Field(ge=1, le=3)
    completeness: int = Field(ge=1, le=3)
    code_quality: int = Field(ge=1, le=3)
    total: int = Field(ge=3, le=9)
    notes: str

    @model_validator(mode="after")
    def accurate_total(self) -> "CandidateScore":
        expected = self.correctness + self.completeness + self.code_quality
        if self.total != expected:
            raise ValueError(f"total must equal component scores ({expected})")
        return self


class ArenaVerifierOutput(StrictModel):
    ranking: list[Literal["A", "B", "C"]] = Field(min_length=1, max_length=3)
    scores: list[CandidateScore] = Field(min_length=1, max_length=3)
    winner_rationale: str

    @model_validator(mode="after")
    def complete_ranking(self) -> "ArenaVerifierOutput":
        ranked = list(self.ranking)
        scored = [score.candidate_id for score in self.scores]
        if len(ranked) != len(set(ranked)) or set(ranked) != set(scored):
            raise ValueError("ranking must contain every scored candidate exactly once")
        return self
